# Eureka Server context path
spring.application.name=eureka-server
server.servlet.context-path=/eureka

server.port=${PORT:8761}

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
